name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'  # Adjust the PHP version as needed
        extensions: 'curl, fileinfo, mbstring, pdo_sqlite, sqlite3'  # Add required extensions
    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    - name: Dump autoload
      run: composer dump-autoload
    - name: Run PHPUnit tests
      run: composer run-script test
    - name: Run PHPSniffer
      run: composer run-script lint